version: '3.8'
services:
  projectone:
    image: projectone:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
